const SWAPPI_URL = "https://swapi.dev/api/";
export const PEOPLE = "people";
export const PLANETS = "planets";
export const STARSHIPS = "starships";
const PAGE = "?page=";
export const FILMS = "films";
export const SWAPPI_PEOPLE = SWAPPI_URL + PEOPLE + PAGE;
export const SWAPPI_PERSON = SWAPPI_URL + PEOPLE;
export const SWAPPI_FILMS = SWAPPI_URL + FILMS;
export const SWAPPI_PLANETS = SWAPPI_URL + PLANETS + PAGE;
export const SWAPPI_PLANET = SWAPPI_URL + PLANETS;
export const SWAPPI_STARSHIPS = SWAPPI_URL + STARSHIPS + PAGE;
export const SWAPPI_STARSHIP = SWAPPI_URL + STARSHIPS;
export const imageURL = "https://starwars-visualguide.com/assets/img/";
export const characters = "characters";
